name: Workflow cleaner
description: Workflow cleaner to timeout long-running jobs
inputs:
  app-id:
    required: true
    description: "The app id from the Github App"
  app-pk:
    required: true
    description: "The private key from the Github App"
  scan-range-days:
    required: false
    default: "2"
    description: "The scan range in days"
  timeout-minutes:
    required: false
    default: "180"
    description: "The timeout for workflows in minutes. Defaults to 180 minutes (3 hours)"
outputs:
  report:
    description: "A markdown table with the jobs cancelled by the action"
runs:
  using: 'node20'
  main: 'dist/index.js'